### PR TITLE
Rebased #76

### PR DESCRIPTION
**Pull request by micah-k**

### CODE REVIEW

**Comment by ptressel** [comment]
Before you commit this, please note you can *remove entirely* any commits that were just mistakes, by doing a rebase and refactoring your commits.  E.g. the pair of commits that add and remove the same file.  If you have experimental work, you can do that on a branch, and then just include clean, final commits to put in the shared repository.

**Comment by ptressel** [comment]
If you need help with refactoring the commits or with using rebase, let me know.  Did you find someone to do a code review?

**Comment by ptressel** [comment]
Tyler --  Did you see my comment?  This should be cleaned up before merging.  You can "revert" the merge, but it would have to be done before any other changes come in.

**Comment by micah-k** [comment]
I did see the comment, as did some of the other students; however, we
decided that since cleaning out redundant commits would be purely cosmetic,
it's better to leave the history as is for posterity.

**Comment by ptressel** [comment]
It's not "purely cosmetic".  It adds the storage required for the useless file to the repo.

**Comment by ptressel** [comment]
If the "history" is just the committer's mistake, it does not need to be preserved for everyone else.  Nor do lots of little temporary commits.  It is very common for people to clean up and refactor their commits into a logical, meaningful set, in which each commit has related changes that belong together.

**Comment by micah-k** [comment]
Ah, now I see what your point is. I had assumed that having the mistaken
commit in the history simply stated, "Micah messed something up here," but
if it takes up actual space beyond that simple annotation then it's
definitely worth cleaning up. However, the pull request has already gone
through (as far as I can tell); should we still edit out the useless
commits?

**Comment by ptressel** [comment]
Right, git must preserve everything that allows it to check out any prior revision.  (On another project, we went so far as to abandon a repo that had a huge amount of old unneeded stuff, and just keep that for the history, because that repo was taking so long for people to clone.)

Once it has been pulled into the live repo, it's generally considered too late to change, as that would require a forced push, and would Rewrite History in a public repo,  That's only "safe" so long as you know that no-one has done a pull from the repo.  GitHub offers a "revert" button for a while after a pull request is accepted, but it is gone now.  So it's likely too late now.

No-one needs to know if you "messed up".  :-D  That's between you and your local repo.  It's fine to do all the tidying up before the pull request, and then look like an expert online.  I have all sorts of temporary and partial commits in my local repos that I refactor before pushing to GitHub.  (In fact, I have some temporary commits in my personal repos on GitHub that I use for "backup" -- commits with messages like "emergency commit, laptop dying".)

Refactoring commits with interactive rebase is a bit tricky the first time, but it's a really useful tool, and good to get comfortable with.

**Pull request merged**
