### PR TITLE
Merge High Level code from Self-Drive

### PR DESCRIPTION
**Pull request by TylerFolsom**

### CODE REVIEW

**Comment by ptressel** [comment]
Please do not merge this.  There is something wrong...  It appears to lump in material that should be in Taylor's PR.  These should not me mixed up in one PR.  Let's get Taylor's PR back, and you can make your changes in a separate PR.

**Comment by ptressel** [comment]
There is something doubly wrong with this...  The cleanup PR was already merged.  Again, DO NOT MERGE THIS.  It will have to be backed out.

**Comment by TylerFolsom** [comment]
Pat –

 

OK.  There is nothing in my PR that I am trying to change, so it can be abandoned. My intent is to move the High Level code from Elcano/SelfDrive to Elcano/Elcano.  It looks like I  did not sync my own repo with Taylor’s changes.

 

*	Tyler

**Comment by TylerFolsom** [comment]
Pull request withdrawn.  Need to check that all current files are in repository.

**Pull request closed without merging**
